# Generated by Django 4.2.6 on 2023-10-11 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grouped_item', models.CharField(max_length=30, unique=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('units_used', models.PositiveIntegerField(default=0)),
                ('units_available', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sqlserverconn',
            fields=[
                ('Item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(db_index=True, max_length=30)),
                ('Units', models.PositiveIntegerField()),
                ('Unit_of_measurement', models.CharField(max_length=15)),
                ('Unit_cost', models.FloatField()),
                ('Date', models.DateField()),
                ('Subtotal', models.FloatField(default=0)),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlserverconns', to='app.groupeditems')),
            ],
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('units_issued', models.PositiveIntegerField(default=0)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_items', to='app.groupeditems')),
            ],
        ),
        migrations.AddIndex(
            model_name='groupeditems',
            index=models.Index(fields=['grouped_item', 'total_units'], name='grouped_item_total_units_idx'),
        ),
        migrations.AddIndex(
            model_name='sqlserverconn',
            index=models.Index(fields=['Item'], name='item_idx'),
        ),
    ]
