# Generated by Django 4.2.8 on 2024-07-29 22:58

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Custom_UOM',
            fields=[
                ('UOM', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupedItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grouped_item', models.CharField(max_length=30, unique=True)),
                ('total_units', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('used_units', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('units_available', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('building_area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('materials', models.JSONField(blank=True, null=True)),
                ('building_codes', models.TextField(blank=True)),
                ('site_conditions', models.TextField(blank=True)),
                ('drawings', models.URLField(blank=True, null=True)),
                ('project_requirements', models.TextField(blank=True)),
                ('sustainability_considerations', models.TextField(blank=True)),
                ('external_factors', models.TextField(blank=True)),
                ('estimated_completion_time', models.PositiveIntegerField(blank=True, help_text='Estimated completion time in days', null=True)),
                ('required_employees', models.PositiveIntegerField(blank=True, help_text='Estimated number of employees required', null=True)),
                ('detailed_materials_list', models.JSONField(blank=True, help_text='Detailed list of materials including types and quantities')),
                ('feasibility_report', models.TextField(blank=True, help_text='Detailed feasibility report generated by AI')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_type', models.CharField(max_length=20)),
                ('NOL', models.PositiveIntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('labourer_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('sub_total', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('units_issued', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('units_returned', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('units_used', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_items', to='app.groupeditems')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='groupeditems',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employees', to='app.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='sqlserverconn',
            fields=[
                ('Item_id', models.BigAutoField(db_column='Item_id', primary_key=True, serialize=False)),
                ('Item', models.CharField(db_column='Item', db_index=True, max_length=30)),
                ('Item_Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Units', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('Unit_of_measurement', models.CharField(blank=True, max_length=15, null=True)),
                ('Unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('Date', models.DateField()),
                ('Subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlserverconns', to='app.groupeditems', to_field='grouped_item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['Item'], name='item_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='groupeditems',
            index=models.Index(fields=['grouped_item', 'total_units'], name='grouped_item_total_units_idx'),
        ),
    ]
