# Generated by Django 4.2.8 on 2024-07-31 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feasibility_report',
        ),
    ]
