# Generated by Django 4.2.8 on 2024-03-01 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_talent', to='app.tenant'),
        ),
        migrations.AlterField(
            model_name='sqlserverconn',
            name='grouped_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlserverconns', to='app.groupeditems', to_field='grouped_item'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
