# Generated by Django 4.2.8 on 2024-08-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_feasibility_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='drawings',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
