# Generated by Django 4.2.8 on 2024-05-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_alter_customuser_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labour',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sqlserverconn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
