# Generated by Django 4.2.6 on 2023-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_issueitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeditems',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
