# Generated by Django 4.2.8 on 2024-08-03 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_drawings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeditems',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupeditems', to='app.project'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='app.project'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='labour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sqlserverconn',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlserverconns', to='app.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.project'),
        ),
    ]
