# Generated by Django 4.2.6 on 2023-10-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_groupeditems_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlserverconn',
            name='Item_Description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
