# Generated by Django 4.2.6 on 2023-10-18 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sqlserverconn_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOM', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='groupeditems',
            name='Units_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='groupeditems',
            name='total_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='groupeditems',
            name='units_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='groupeditems',
            name='units_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='issueitem',
            name='units_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='return_item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=20)),
                ('units_returned', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='app.groupeditems')),
            ],
        ),
    ]
