# Generated by Django 4.2.6 on 2023-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_custom_uom_groupeditems_units_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_uom',
            name='id',
        ),
        migrations.AlterField(
            model_name='custom_uom',
            name='UOM',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
