# Generated by Django 4.2.6 on 2023-10-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sqlserverconn_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlserverconn',
            name='Item_id',
            field=models.BigAutoField(db_column='Item_id', primary_key=True, serialize=False),
        ),
    ]
