# Generated by Django 4.2.6 on 2023-10-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_labour_remove_groupeditems_units_returned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupeditems',
            old_name='units_used',
            new_name='used_units',
        ),
    ]
