# Generated by Django 4.2.6 on 2023-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_units_used_groupeditems_used_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlserverconn',
            name='Unit_of_measurement',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
