# Generated by Django 4.2.6 on 2023-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_sqlserverconn_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlserverconn',
            name='Units',
            field=models.FloatField(default=0),
        ),
    ]
