# Generated by Django 4.2.6 on 2023-10-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_sqlserverconn_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='labour_type',
            field=models.CharField(max_length=20),
        ),
    ]
