# Generated by Django 4.2.6 on 2023-10-31 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_labour_labour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour121',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_type', models.CharField(max_length=20)),
                ('NOL', models.PositiveIntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('labourer_cost', models.FloatField()),
                ('sub_total', models.FloatField(default=0)),
            ],
        ),
    ]
