# Generated by Django 4.2.6 on 2023-10-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_labour121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labour121',
        ),
    ]
